name: Evaluation

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
<<<<<<< HEAD
        uses: actions/setup-python@v2
=======
        uses: actions/setup-python@v4
>>>>>>> dca85de (Initial commit)
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
<<<<<<< HEAD

      - name: Test with pytest
        timeout-minutes: 2
        run: |
          pytest -vv --timeout=20
<<<<<<< HEAD
<<<<<<< HEAD


  bash_tests:
    name: Bash Tests
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          chmod +x *.sh

      - name: Launch servers into background
        run: |
          bash ./setup.sh > load_balancer.txt &

      - name: stress test on standby
        run: |
          bash ./stress_test.sh

      - name: load_balancer Logs
        uses: actions/upload-artifact@v2
        with:
          name: load_balancer logs
          path: load_balancer.txt
          retention-days: 1
=======
>>>>>>> 4333182 (Initial commit)
=======
=======
      
      - name: Launch DHT into background
        run: |
          python3 DHT.py --savelog &
          PID=$!
          sleep 1
          ps -p $PID > /dev/null

      - name: Test with pytest
        timeout-minutes: 3 
        run: |
          sleep 15 
          pytest

      - name: DHT Logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: DHT logs
          path: dht.txt
          retention-days: 1
>>>>>>> dca85de (Initial commit)
>>>>>>> cecd2bc (Initial commit)
